# title of website
title: 大强导航

# description of website
description: dqtx760's navigation site

# favicon of website
favicon: "https://github.com/dqtx760.png?size=40"

# your website url
url: https://dqtx760.github.io/999/

# github profile url
github: "https://github.com/dqtx760/999"

# footer message
footer: © 2025 大强个人专用导航，建议收藏！

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  # 设置网站默认主题样式为浅色
  style: light
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Github
          description: 全球最大的代码托管平台。
          url: https://github.com/
        - name: vercel
          description: 网站部署云平台
          url: https://vercel.com/
        - name: Cloudflare
          description: 域名托管/反向代理。
          url: https://dash.cloudflare.com/
        - name: Greasy
          description: 油猴脚本下载
          url: https://greasyfork.org/zh-CN   
        - name: IP查询
          description: IP4/ipv6查询。
          url: https://ip.sb/
        - name: ping
          description: 测试网站的ping连接
          url: https://ping.pe/            
        - name: 短链
          description: 长连接转短链接
          url: https://suo.im/
        - name: 临时邮箱
          description: 十秒钟内收到邮。
          url: https://tempmail.cn/   
    - name: 人工智能
      sites:
        - name: ChatGPT
          description: 写作辅助工具
          url: https://chat.openai.com/
        - name: Gemini
          description: 代码速度快
          url: https://gemini.google.com/
        - name: Grok
          description: 马斯克的AI工具
          url: https://grok.com/ 
        - name: perplexity
          description: AI搜索牛逼
          url: https://www.perplexity.ai/
        - name: Cherry-studio      
          description: AI客户端
          url: https://www.cherry-ai.com/
        - name: 仙宫云
          description: AI云服务器租赁
          url: https://www.xiangongyun.com/register/TLJSYM
        - name: 提示词优化
          description: 提示词优化器
          url: https://prompt.always200.com/       
        - name: 提示词合集
          description: 各大AI博主的提示词合集
          url: https://www.prompterhub.cn/best-practices              
    - name: 电影网站
      sites:
        - name: VeloraTV
          description: UI感觉漂亮高清
          url: https://veloratv.ru/
        - name: Flixer
          description: 高清无广告
          url: https://flixer.su/
        - name: 低端电影
          description: 欧美剧，页面感觉无光
          url:  https://ddys.pro/
        - name: 袋鼠影视
          description: 欧美剧，页面感觉无光
          url:  https://dsdytv.com/  
        - name: my TV
          description: 电视直播软件
          url: https://github.com/lizongying/my-tv-0
        - name: 网易爆米花
          description: 网盘刮削神器
          url: https://bmh.163.com/
        - name: ZyPlayer
          description: 电脑影视播放器
          url: https://github.com/Hiram-Wong/ZyPlayer
        - name: iptv-api 
          description: 自编译直播源
          url: https://xodnytdcaw.feishu.cn/wiki/Id2KwbqcgiFzV9kfh83cZ3brnod?fromScene=spaceOverview
    - name: 壁纸网站
      sites:
        - name: 遮风壁纸
          description: 每天可下载5张
          url: https://haowallpaper.com/
        - name: 拾光壁纸
          description: 还可以
          url: https://netbian.timeline.ink/home
        - name: 致美化
          description: 不错
          url: https://zhutix.com/wallpaper/
        - name: 暖糖壁纸
          description: 不经常用
          url: https://www.nuantang.net/
        - name: 极简壁纸
          description: 很少用
          url: https://bz.zzzmh.cn/index?time=5e4rrofz21
        - name: alphacoders
          description: 质量很高
          url: https://alphacoders.com
        - name: 4kwallpapers
          description: 很多人用
          url: https://4kwallpapers.com/
        - name: wallspic
          description: 手机壁纸
          url: https://wallspic.com/cn    
    - name: 脑洞运营
      sites:
        - name: 热榜
          description: 每日热点追踪
          url: https://newsnow.busiyi.world/
        - name: mdnice
          description: mrkdown排版
          url: https://editor.mdnice.com/
        - name: openai
          description: 文字转语音
          url: https://www.openai.fm/
        - name: get笔记
          description: AI笔记
          url: https://www.biji.com/note         
    - name: 图片工具
      sites:
        - name: 美图设计师
          description: 封面制作
          url: https://www.designkit.com
        - name: 即梦AI
          description: 字节文生图工具
          url: https://jimeng.jianying.com/ai-tool/image/generate     
        - name: 拼图
          description: 网页端
          url: https://collagemaker.tools/photo/
        - name: 截图美化
          description: 效果不错
          url: https://shots.so/
        - name: 去水印
          description: 无论水印多复杂
          url: https://www.watermarkremover.io/zh       
        - name: pixabay
          description: 图片素材
          url: https://pixabay.com/images/search
        - name: 二维码
          description: 二维码生成
          url: https://qrbtf.com/zh
        - name: 图标
          description: 图标素材
          url: https://icon-icons.com/zh/
    - name: 文件传输
      sites:
        - name: landrop
          description: 局域网传输
          url: https://landrop.app/
        - name: openlist
          description: 网盘挂载工具
          url: https://github.com/OpenListTeam/OpenList          
        - name: piclist
          description: 图床工具
          url: https://piclist.cn/
        - name: 任推帮
          description: 网盘拉新赚收益
          url: https://dt.bd.cn/#/pages/login/register?invite_code=577546            
        - name: 4275
          description: 无需注册登录
          url: https://4275.com/
        - name: 直链
          description: 蓝奏云/123云盘生成
          url: https://lz.qaiu.top/
        - name: 蓝奏云
          description: 一个蓝奏云增强脚本
          url: https://greasyfork.org/zh-CN/scripts/419224-%E8%93%9D%E5%A5%8F%E4%BA%91%E7%BD%91%E7%9B%98%E5%A2%9E%E5%BC%BA
        - name: 123
          description: 一个123增强脚本
          url: https://greasyfork.org/zh-CN/scripts/519353-123%E4%BA%91%E7%9B%98%E8%A7%A3%E9%94%81        
    - name: 网络相关
      sites:
        - name: Hiddify
          description: 代理工具
          url: https://github.com/hiddify/hiddify-app/releases/tag/v2.0.5  
        - name: 节点
          description: 科学上网节点
          url: https://ccv.gwzxwk.com/#/register?code=L2FOV7Yb     
        - name: openwrt 
          description: openwrt 软路由固件
          url: https://github.com/kiddin9/Kwrt    
        - name: Sms
          description: 接码平台
          url:  https://sms-activate.guru/?ref=12307132         
        - name: steampp
          description: GitHub访问加速
          url: https://steampp.net/       
        - name: 2FA
          description: 2FA工具
          url: https://2fa.run/
        - name: github加速
          description: GitHub下载加速
          url: https://yishijie.gitlab.io/ziyuan/     
        - name: Xget
          description: git clone加速
          url:  https://xuc.xi-xu.me/    
    - name: 重装系统
      sites:
        - name: Massgrave
          description: Win镜像下载
          url: https://massgrave.dev/windows_ltsc_links  
        - name: itellyou
          description: Win镜像下载
          url: https://msdn.itellyou.cn/?ang=2h-cn     
        - name: uupdump 
          description: Win镜像下载
          url: https://uupdump.net/    
        - name: Cmdpe
          description: Win镜像下载
          url:  https://www.cmdpe.com/post/246.html    
        - name: Ventoy
          description: U启工具
          url: https://www.ventoy.net/cn/download.html  
        - name: Rufus
          description: U启工具
          url: https://rufus.ie/zh/     
        - name: WePE 
          description: U启工具
          url: https://www.wepe.com.cn/download.html    
        - name: balena
          description: U启工具
          url: https://etcher.balena.io/  
     - name: 苹果相关
      sites:
        - name: hubweb
          description: Win镜像下载
          url: https://hubweb.cn/  
        - name: 快捷指令
          description: 少数派旗下站点
          url: https://sspai.com/page/playbook/zh-CN     
        - name: gofans
          description: 限免APP
          url: https://gofans.cn/    
        - name: IMEI查询
          description: 苹果序列号查询
          url:  https://www.guofenjianding.com/index             
    - name: 关于本站
      sites:
        - name: 大强官网
          description: 导航页
          url: https://dqtx.cc
        - name: 大强附件表
          description: 往期视频附件
          url: https://88.dqtx.cc/main.html#/README.md
        - name: 远程支持
          description: 远程解决电脑问题
          url: https://www.742112.xyz/
        - name: chrome插件
          description: chrome优质插件
          url: https://discreet-ringer-ef6.notion.site/chrome-19b351994e40800db8fcd988348f533a
