# title of website
title: dav

# description of website
description: dqtx760's navigation site

# favicon of website
favicon: "https://github.com/dqtx760.png?size=40"

# your website url
url: https://dqtx760.github.io/dav/

# github profile url
github: "742112.xyz"

# footer message
footer: © 2021-2021 @dqtx760

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: false
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: Github
          description: 全球最大的代码托管平台。
          url: https://github.com/
        - name: vercel
          description: 网站部署云平台
          url: https://vercel.com/
        - name: Cloudflare
          description: 域名托管/反向代理。
          url: https://dash.cloudflare.com/
        - name: 白噪音
          description: 保持专注和静谧
          url: https://yuyin.ognai.com/     
    - name: AI工具
      sites:
        - name: ChatGPT
          description: 写作辅助工具
          url: https://chat.openai.com/
        - name: Gemini
          description: 代码速度快
          url: https://gemini.google.com/
        - name: Grok
          description: 马斯克的AI工具
          url: https://grok.com/ 
        - name: perplexity
          description: AI搜索牛逼
          url: https://www.perplexity.ai/
        - name: 即梦
          description: 即梦AI
          url: https://jimeng.jianying.com/ai-tool/image/generate         
        - name: cherry-studio
          description: AI客户端
          url: https://www.cherry-ai.com/
        - name: 仙宫云
          description: AI云服务器租赁平台
          url: https://www.xiangongyun.com/register/TLJSYM
        - name: 提示词优化
          description: 提示词优化器
          url: https://prompt.always200.com/
          
    - name: 电影网站
      sites:
        - name: VeloraTV
          description: UI感觉漂亮高清
          url: https://veloratv.ru/
        - name: 4K影视
          description: 不错,高清
          url: https://www.4kvm.net/
        - name: 低端电影
          description: 欧美剧，页面感觉无光
          url:  https://ddys.pro/
        - name: 袋鼠影视
          description: 欧美剧，页面感觉无光
          url:  https://dsdytv.com/  

    - name: 壁纸网站
      sites:
        - name: 遮风壁纸
          description: 每天可下载5张
          url: https://haowallpaper.com/
        - name: 拾光壁纸
          description: 还可以
          url: https://netbian.timeline.ink/home
        - name: 致美化
          description: 不错
          url: https://zhutix.com/wallpaper/
        - name: 暖糖壁纸
          description: 不经常用
          url: https://www.nuantang.net/
        - name: 极简壁纸
          description: 很少用
          url: https://bz.zzzmh.cn/index?time=5e4rrofz21
        - name: alphacoders
          description: 质量很高
          url: https://alphacoders.com
        - name: 4kwallpapers
          description: 很多人用
          url: https://4kwallpapers.com/
        - name: wallspic
          description: 手机壁纸
          url: https://wallspic.com/cn    
    - name: 制图工具
      sites:
        - name: 美图设计师
          description: 
          url: https://www.designkit.com
        - name: 在线PS
          description: 
          url: https://www.photopea.com/
        - name: 拼图
          description: 
          url: https://collagemaker.tools/photo/
        - name: 截图美化
          description: 
          url: https://shots.so/
        - name: 去水印
          description: 无论水印多复杂
          url: https://www.watermarkremover.io/zh       
         - name: pixabay
          description: 图片素材
          url: https://pixabay.com/images/search
            
    - name: 文件传输
      sites:
        - name:4275 
          description: 
          url: https://4275.com/
        - name: 直链
          description: 蓝奏云/123云盘生成
          url: https://lz.qaiu.top/
        - name: piclist
          description: 图床工具
          url: https://piclist.cn/
        - name: openlist
          description: 
          url: https://doc.oplist.org/
        - name: landrop
          description: 局域网传输
          url: https://landrop.app/
        - name: 蓝奏云
          description: 一个蓝奏云增强脚本
          url: https://github.com/XIU2/UserScript
    - name: 网络相关
      sites:
        - name: Hiddify
          description: 代理工具
          url: https://github.com/hiddify/hiddify-app/releases/tag/v2.0.5  
        - name: 节点
          description: 科学上网节点
          url:  https://77.dqtx.cc/      
        - name: steampp
          description: 
          url: https://steampp.net/       
        - name: dev-sidecar
          description: 
          url: https://github.com/docmirror/dev-sidecar
        - name: github加速
          description: GitHub文件加速下载
          url: https://yishijie.gitlab.io/ziyuan/     
        - name: Xget
          description: git clone加速
          url:  https://xuc.xi-xu.me/             
    - name: 素材下载
      sites:
        - name: wallhalla
          description: Find awesome high quality wallpapers for desktop and mobile in one place.
          url: https://wallhalla.com/
        - name: 365PSD
          description: Free PSD & Graphics, Illustrations
          url: https://365psd.com/
        - name: Medialoot
          description: Free & Premium Design Resources — Medialoot
          url: https://medialoot.com/
        - name: 千图网
          description: 专注免费设计素材下载的网站
          url: http://www.58pic.com/

    - name: TV资源
      sites:
        - name: Freebiesbug
          description: Hand-picked resources for web designer and developers, constantly updated.
          url: https://freebiesbug.com/
        - name: Freebie Supply
          description: Free Resources For Designers
          url: https://freebiesupply.com/
        - name: 云瑞
          description: 优秀设计资源的分享网站
          url: https://www.yrucd.com/
        - name: 稀土区
          description: 优质设计开发资源分享
          url: https://xituqu.com/
    - name: 协助工具
      sites:
        - name: Sketch
          description: The digital design toolkit
          url: https://sketchapp.com/
        - name: Sketch Measure
          description: Friendly user interface offers you a more intuitive way of making marks.
          url: http://utom.design/measure/
        - name: Sketch App Sources
          description: Free design resources and plugins - Icons, UI Kits, Wireframes, iOS, Android Templates for Sketch
          url: https://www.sketchappsources.com/
        - name: Sketch.im
          description: Sketch 相关资源汇聚
          url: http://www.sketch.im/
    - name: 测试资源
      sites:
        - name: Google Font
          description: Making the web more beautiful, fast, 和 open through great typography
          url: https://fonts.google.com/
        - name: Typekit
          description: Quality fonts from the world’s best foundries.
          url: https://typekit.com/
        - name: 方正字库
          description: 方正字库官方网站
          url: http://www.foundertype.com/
        - name: 字体传奇网
          description: 中国首个字体品牌设计师交流网
          url: http://ziticq.com/

    - name: 关于本站
      sites:
        - name: MockupZone
          description: Mockup Zone is an online store where you can find free and premium PSD mockup files to show your designs in a professional way.
          url: https://mockup.zone/
        - name: Dunnnk
          description: Generate Product Mockups For Free
          url: http://dunnnk.com/
        - name: Graphberry
          description: Free design resources, Mockups, PSD web templates, Icons
          url: http://www.graphberry.com/
        - name: Threed
          description: Generate 3D Mockups right in your Browser
          url: http://threed.io/
